### ISSUE TITLE
Missing documentation link

### ISSUE THREAD

**Issue by psgioia** [nasa/Plot3D_utilities#14]
It appears as though the link for the documentation is broken. Receiving a 404 error

"The site configured at this address does not contain the requested file.

If this is your site, make sure that the filename case matches the URL.
For root URLs (like http://example.com/) you must provide an index.html file."

**Comment by pjuangph** [comment]
Link will be updated to this.
https://nasa.github.io/Plot3D_utilities/build/html/

Thanks for reporting.

**Comment by pjuangph** [comment]
done

**Comment by psgioia** [comment]
Thanks!
