### ISSUE TITLE
File not found error

### ISSUE THREAD

**Issue by ADITYADAS1999** [nasa/Plot3D_utilities#24]
The link to the documentation is not found at the install instruction section

![77885](https://user-images.githubusercontent.com/58718316/192127910-fdd70336-79eb-4ca8-b4d4-ce6e29a20f43.PNG)

**Comment by pjuangph** [comment]
Thanks, I'll take a look on Monday.

**Comment by pjuangph** [comment]
fixed

**Comment by ADITYADAS1999** [comment]
> Thanks, I'll take a look on Monday.

Thanks for fixed the issue @pjuangph 😊
